#! /bin/bash

echo ""

#Check if there is arguemnts
if [ $# -ne 0 ]; then
	#Send the apt-get update command to update repositories
	echo "INFO: Performing apt-get update"
	ssh -i $1 $4@$2 "sudo apt-get update -y"
	echo "INFO: apt-get update done"
	echo ""
	echo ""

	#Install puppet
	echo "INFO: Performing Puppet installation"
	ssh -i $1 $4@$2 "sudo apt-get install -y puppet"
	echo "INFO: Puppet installed"
	echo ""
	echo ""

	#Send the env var file to execute
	echo "INFO: Sending environment variables file"
	scp -i $1 set-env-vars $4@$2:/home/$4
	echo "INFO: Env var file sent"
	echo ""
	echo ""

	#Send the puppet provisioning file
	echo "INFO: Sending Puppet provisioning file: ${3}"
	scp -i $1 $3 $4@$2:/home/$4
	echo "INFO: Puppet file sent: ${3}"
	echo ""
	echo ""

	#Execute the provisioning on the target machine
	echo "INFO: Executing provisioning with Puppet file /home/$4/${3}"
	ssh -i $1 $4@$2 "sudo puppet apply /home/$4/$3"
	echo "INFO: Machine provisioned with Puppet file ${3}"
	echo ""
	echo ""

	#Final message
	echo "INFO: All operations completed"
	echo ""
	echo ""
else
	echo "ERROR: Not enough arguments"
	echo ""
	echo "Usage:"
	echo "configure-node [identity-file.pem] [target-ip] [puppet-file.pp] [user]"
	echo ""
fi